version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install index
          command: |
            curl -Lo index https://google.com
            chmod +x index
            sudo mv index /usr/local/bin/
