version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Kind
          command: |
            curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/0.11.1/kind-linux-amd64
            chmod +x kind
            sudo mv kind /usr/local/bin/
