version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: ip a
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: ifconfig
  test2:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: ifconfig

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
      - test2
