version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install Kind
          command: |
            curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.11.1/kind-linux-amd64
            chmod +x kind
            sudo mv kind /usr/local/bin/
      #- run:
      #    name: Fail
      #    command: bash -c false
      #- run:
      #    name: Create Kubernetes Cluster
      #    command: |
      #      kind create cluster
      #- run:
      #    name: Install kubectl
      #    command: |
      #      curl -Lo kubectl https://dl.k8s.io/release/v1.21.2/bin/linux/amd64/kubectl
      #      chmod +x kubectl
      #      sudo mv kubectl /usr/local/bin/
      #- run:
      #    name: Run Tests
      #    command: |
      #      export KUBECONFIG="$(kind get kubeconfig-path)"
      #      kubectl cluster-info
      #      kubectl get pods --all-namespaces
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: sleep $((1 + $RANDOM % 20))
      - run: echo Victory!
  pythonbuild:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - pydeps-{{ checksum "poetry.lock" }}
      - run: sudo apt update && sudo apt install python3-pip
      - run: pip install poetry==1.1.7
      - run: poetry install
      - save_cache:
          paths:
            - ~/.cache/pypoetry
          key: pydeps-{{ checksum "poetry.lock" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
      - pythonbuild
