version: 2
jobs:
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: working 1
          command: sleep 10 && echo 1
          background: true
      - run:
          name: working 2
          command: sleep 10 && echo 2
          background: true

      - run:
          name: w3
          command: sleep 5 && echo 3
          background: true
      - run:
          name: waiter
          command: sleep 15


workflows:
  version: 2
  build_and_test:
    jobs:
      - test
