version: 2.1
orbs:
  minikube: takescoop/minikube@1.0.1
  helm: circleci/helm@1.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    parameters:
      helm-version:
        default: "v3.2.4"
        type: string
      kube-version:
        default: stable
        type: string
    steps:
      - minikube/install:
          version: latest
      - minikube/start:
          kubernetes-version: << parameters.kube-version >>
      - minikube/install-kubectl:
          kubectl-version: stable
      - helm/install-helm-chart:
          chart: stable/grafana
          release-name: grafana-release
          helm-version: << parameters.helm-version >>
          wait: false
      - helm/install-helm-chart:
          chart: stable/redis
          release-name: redis
          helm-version: << parameters.helm-version >>
          wait: false
          update-repositories: false

      - run: for i in $(seq 1 10); do kubectl get po -A; sleep 2; done
      - run: kubectl version


workflows:
  version: 2
  build_kube:
    jobs:
      - build:
          kube-version: "1.19.1"
      - build:
          kube-version: "1.21.1"
