version: 2.1
orbs:
  minikube: takescoop/minikube@1.0.1
  helm: circleci/helm@1.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - minikube/install:
          version: latest
      - minikube/start:
          kubernetes-version: stable
      - minikube/install-kubectl:
          kubectl-version: stable
      - helm/install-helm-chart:
          chart: stable/grafana
          helm-version: v3.2.4
          release-name: grafana-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

