version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
      - image: mongo:4.2
    steps:
      - run:
          name: step1
          command: sleep 10 && echo 1
          background: true
      - run:
          name: step2
          command: sleep 10 && echo 2
          background: true
      - run:
          name: step3
          command: sleep 10 && echo 3
          background: true
      - run:
          name: step4 Mongo is available on localhost
          command: |
            sleep 11
            curl -sSJL https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
            sudo apt update
            sudo apt install mongodb-org
            mongo localhost --eval 'db.serverStatus()'
workflows:
  version: 2
  builder:
    jobs:
      - build

